apiVersion: v1                         # API version for this resource
kind: PersistentVolumeClaim            # Resource type: PersistentVolumeClaim
metadata:
  name: jenkins-pvc                    # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce                    # RWO means volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 10Gi                    # Amount of storage requested by this claim
  storageClassName: standard           # References the StorageClass that will provision the volume
