apiVersion: v1                         # API version for Service resources
kind: Service                          # Resource type: Service
metadata:
  name: jenkins-service                # Name of the service
spec:
  type: NodePort                       # Service type: makes service accessible on a port on each node
  selector:
    app: jenkins-set                   # Selects pods with this label to send traffic to
  ports:
    - port: 8080                       # Port the service exposes
      targetPort: 8080                 # Port on the pod that traffic is sent to
      nodePort: 30080                  # Port on each node where service is accessible (30000-32767)
