apiVersion: apps/v1                    # API version for Deployment resources
kind: Deployment                       # Resource type: Deployment
metadata:
  name: jenkins-deploy                 # Name of the deployment
  labels:
    app: jenkins-set                   # Label applied to the deployment itself
spec:
  replicas: 2                          # Number of pod replicas to maintain
  strategy:
    type: RollingUpdate                # Update strategy: gradually replace pods
    rollingUpdate:
      maxSurge: 2                      # Max number of pods that can exceed the replica count during update
      maxUnavailable: 0                # Max number of pods that can be unavailable during update
  selector:
    matchLabels:
      app: jenkins-set                 # Selects which pods are managed by this deployment
  template:
    metadata:
      labels:
        app: jenkins-set               # Labels applied to the pods created by this template
    spec:
      volumes:
        - name: local-volume           # Name of the volume, referenced by volumeMounts
          persistentVolumeClaim:
            claimName: jenkins-pvc     # Name of the PVC to use for this volume
      containers:
        - name: jenkins                # Container name
          image: jenkins/jenkins:latest # Container image to use
          ports:
            - containerPort: 8080      # Port that Jenkins exposes inside the container
          volumeMounts:
            - name: local-volume       # Name of the volume to mount (must match volume name above)
              mountPath: /var/jenkins_home # Where to mount the volume in the container
