apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: my-jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008

